# Two dimensional toy data (1)

Example adopted from:

* 栗原考次, & 石岡文生. (2021). エシェロン解析: 階層化して視る時空間データ. 共立出版.

In [1]:
# %load_ext autoreload
# %autoreload 2
import echelon
echelon.__version__

'1.0.0'

In [2]:
from IPython.display import Markdown, display
import numpy as np

### Data
data = np.array([
    [2, 8, 24, 5, 3],
    [1, 10, 14, 22, 15],
    [4, 21, 19, 23, 25],
    [16, 20, 12, 11, 17],
    [13, 6, 9, 7, 18]
])

## Echelon construction

In [3]:
from echelon.api import TwoDimEchelonAnalysis
analyzer = TwoDimEchelonAnalysis()
result = analyzer(data)
result

/Users/teshima/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/numpy/lib/function_base.py:4454: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asarray(arr)
/Users/teshima/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/scipy/sparse/compressed.py:746: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)


Result_EchelonAnalysis(peak_echelons=[[14, 13, 8], [2], [11, 16], [24]], foundation_echelons=[[12], [19, 15, 9], [7, 20, 17, 18, 6, 22, 1, 23, 21, 3, 10, 4, 0, 5]], hierarchy_tree=Node('/6'), oracle=<echelon.oracle.NdarrayEchelonOracle object at 0x7f8be8008240>)

In [4]:
def _echelon_indicator(echelon):
    _W = np.zeros(data.shape, dtype='int8')
    for ind in echelon:
        _W[np.unravel_index(ind, shape=data.shape)] = 1
    return _W

for i, echelon in enumerate(result.peak_echelons):
    display(Markdown(f'### Peak Echelon {i+1}'))
    print(_echelon_indicator(echelon))

for i, echelon in enumerate(result.foundation_echelons):
    display(Markdown(f'### Foundation Echelon {i+1}'))
    print(_echelon_indicator(echelon))
    
print(analyzer.dendrogram(result))

### Peak Echelon 1

[[0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Peak Echelon 2

[[0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Peak Echelon 3

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]]


### Peak Echelon 4

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]


### Foundation Echelon 1

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Foundation Echelon 2

[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [1 0 0 0 1]
 [0 0 0 0 0]]


### Foundation Echelon 3

[[1 1 0 1 1]
 [1 1 1 0 0]
 [1 0 0 0 0]
 [0 0 1 1 0]
 [1 1 1 1 0]]
E7(7): [5, 0, 4, 10, 3, 21, 23, 1, 22, 6, 18, 17, 20, 7]
 (max: 14)

├── E6(19): [9, 15, 19]
│    (max: 17)
│   
│   ├── E5(12): [12]
│   │    (max: 19)
│   │   
│   │   ├── E3(11): [16, 11]
│   │   │    (max: 21)
│   │   │   
│   │   └── E1(14): [8, 13, 14]
│   │        (max: 25)
│   │       
│   └── E4(24): [24]
│        (max: 18)
│       
└── E2(2): [2]
     (max: 24)
    


## Echelon dendrogram

In [5]:
print(analyzer.dendrogram(result))

E7(7): [5, 0, 4, 10, 3, 21, 23, 1, 22, 6, 18, 17, 20, 7]
 (max: 14)

├── E6(19): [9, 15, 19]
│    (max: 17)
│   
│   ├── E5(12): [12]
│   │    (max: 19)
│   │   
│   │   ├── E3(11): [16, 11]
│   │   │    (max: 21)
│   │   │   
│   │   └── E1(14): [8, 13, 14]
│   │        (max: 25)
│   │       
│   └── E4(24): [24]
│        (max: 18)
│       
└── E2(2): [2]
     (max: 24)
    


## Echelon clusters

In [6]:
import pandas as pd
pd.options.display.max_columns = None # Do not omit columns

_df = analyzer.cluster(result)
_df['representatives'] = _df['representatives'].map(lambda x: str(x[0]) + ' Zone')
pd.DataFrame(_df['indices'].to_list()).fillna('').set_index(_df['representatives'].rename('Zone'))

0   1   2   3   4   5   6   7   8   9   10  11  12  13 14 15 16 17
Zone                                                                       
14 Zone  14  13   8  12  19   9   7  17  18   6  22   1  23  21  3  4  0  5
2 Zone    2   7   6   1   3   4   0   5                                    
11 Zone  11  16  12  15   7  20  17  18   6  22   1  23  21  10  0  5      
24 Zone  24  19  18  23

## Hotspot detection

In [7]:
from IPython.display import Markdown, display
display(Markdown('### Poisson score'))
display(analyzer.hotspots(result))

### Poisson score

spot     score  c(Z)  log_lambda
8                [12, 11, 16, 14, 13, 8, 24, 19]  1.278939   165    1.278939
9            [12, 11, 16, 14, 13, 8, 24, 19, 15]  1.272521   181    1.272521
6                        [11, 16, 14, 13, 8, 12]  1.258604   130    1.258604
10        [12, 11, 16, 14, 13, 8, 24, 19, 15, 9]  1.257298   196    1.257298
11  [19, 15, 9, 12, 11, 16, 14, 13, 8, 24, 2, 7]  1.171224   234    1.171224
2                                    [14, 13, 8]  1.082767    70    1.082767
1                                       [14, 13]  0.934978    48    0.934978
5                                       [11, 16]  0.868353    41    0.868353
0                                           [14]  0.647124    25    0.647124
3                                            [2]  0.628238    24    0.628238
4                                           [11]  0.565938    21    0.565938
7                                           [24]  0.493114    18    0.493114