# One dimensional toy data

In [1]:
# %load_ext autoreload
# %autoreload 2

import numpy as np

### Data
h = np.array([1, 2, 3, 4, 3, 4, 5, 4, 3, 2, 3, 4, 5, 6, 5, 6, 7, 6, 5, 4, 3, 2, 1, 2, 1])

W = np.zeros((25, 25), dtype='int8')
W[np.eye(len(W), k=1, dtype='bool')] = 1
W[np.eye(len(W), k=-1, dtype='bool')] = 1

In [2]:
import pandas as pd
pd.DataFrame(W)

0   1   2   3   4   5   6   7   8   9   ...  15  16  17  18  19  20  21  \
0    0   1   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1    1   0   1   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2    0   1   0   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3    0   0   1   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4    0   0   0   1   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
5    0   0   0   0   1   0   1   0   0   0  ...   0   0   0   0   0   0   0   
6    0   0   0   0   0   1   0   1   0   0  ...   0   0   0   0   0   0   0   
7    0   0   0   0   0   0   1   0   1   0  ...   0   0   0   0   0   0   0   
8    0   0   0   0   0   0   0   1   0   1  ...   0   0   0   0   0   0   0   
9    0   0   0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   
10   0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
11   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
12   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
13   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
14   0   0   0   0   0   0   0   0   0   0  ...   1   0   0   0   0   0   0   
15   0   0   0   0   0   0   0   0   0   0  ...   0   1   0   0   0   0   0   
16   0   0   0   0   0   0   0   0   0   0  ...   1   0   1   0   0   0   0   
17   0   0   0   0   0   0   0   0   0   0  ...   0   1   0   1   0   0   0   
18   0   0   0   0   0   0   0   0   0   0  ...   0   0   1   0   1   0   0   
19   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   1   0   1   0   
20   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   1   
21   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   1   0   
22   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   
23   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
24   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

    22  23  24  
0    0   0   0  
1    0   0   0  
2    0   0   0  
3    0   0   0  
4    0   0   0  
5    0   0   0  
6    0   0   0  
7    0   0   0  
8    0   0   0  
9    0   0   0  
10   0   0   0  
11   0   0   0  
12   0   0   0  
13   0   0   0  
14   0   0   0  
15   0   0   0  
16   0   0   0  
17   0   0   0  
18   0   0   0  
19   0   0   0  
20   0   0   0  
21   1   0   0  
22   0   1   0  
23   1   0   1  
24   0   1   0  

[25 rows x 25 columns]

In [3]:
from echelon.api import EchelonAnalysis
analyzer = EchelonAnalysis()
result = analyzer(h, W)
result

/Users/teshima/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/numpy/lib/function_base.py:4454: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asarray(arr)


Result_EchelonAnalysis(peak_echelons=[[16, 17, 15], [13], [6, 5, 7], [3], [23]], foundation_echelons=[[12, 14, 18, 19, 11, 10, 20], [2, 4, 8], [1, 9, 21], [0, 22, 24]], oracle=<echelon.oracle.NdarrayEchelonOracle object at 0x7fe671cc4b38>)

In [4]:
def _echelon_indicator(echelon):
    A = np.zeros(h.shape, dtype='int8')
    for e in echelon:
        A[e] = 1
    return A

for i, echelon in enumerate(result.peak_echelons):
    print(f'Peak Echelon {i+1}')
    print(_echelon_indicator(echelon))

for i, echelon in enumerate(result.foundation_echelons):
    print(f'Foundation Echelon {i+1}')
    print(_echelon_indicator(echelon))


Peak Echelon 1
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0]
Peak Echelon 2
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
Peak Echelon 3
[0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Peak Echelon 4
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Peak Echelon 5
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
Foundation Echelon 1
[0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 1 1 1 0 0 0 0]
Foundation Echelon 2
[0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Foundation Echelon 3
[0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
Foundation Echelon 4
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1]


In [5]:
from echelon.test import _visualize_echelon_hierarchy
hierarchy = analyzer.hierarchy(result)
_visualize_echelon_hierarchy(hierarchy)

9
├── 8
│   ├── 7
│   │   ├── 4
│   │   └── 3
│   └── 6
│       ├── 2
│       └── 1
└── 5


/Users/teshima/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/scipy/sparse/compressed.py:746: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)
