In [1]:
# %load_ext autoreload
# %autoreload 2

from IPython.display import Markdown, display

import numpy as np

### Data
data = np.array([
    [2, 8, 24, 5, 3],
    [1, 10, 14, 22, 15],
    [4, 21, 19, 23, 25],
    [16, 20, 12, 11, 17],
    [13, 6, 9, 7, 18]
])

n, m = data.shape

W = np.zeros((np.prod(data.shape),)*2, dtype='int8')
for i in range(len(W)):
    for delta in [-m, m]:
        j = i + delta
        if (0 <= j) and (j <= len(W)-1):
            W[i, j] = 1
    for delta in [-1, 1]:
        j = i + delta
        if (0 <= j) and (j <= len(W)-1):
            # If j does not move out to a different row
            if (i // m) == (j // m):
                W[i, j] = 1

In [2]:
from echelon.api import EchelonAnalysis
analyzer = EchelonAnalysis()
result = analyzer(data.flatten(), W)
result

/Users/teshima/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/numpy/lib/function_base.py:4454: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asarray(arr)


Result_EchelonAnalysis(peak_echelons=[[14, 13, 8], [2], [11, 16], [24]], foundation_echelons=[[12], [19, 15, 9], [7, 20, 17, 18, 6, 22, 1, 23, 21, 3, 10, 4, 0, 5]], oracle=<echelon.oracle.NdarrayEchelonOracle object at 0x7fe2e145a128>)

In [3]:
def _echelon_indicator(echelon):
    _W = np.zeros(data.shape, dtype='int8')
    for ind in echelon:
        _W[np.unravel_index(ind, shape=data.shape)] = 1
    return _W

for i, echelon in enumerate(result.peak_echelons):
    display(Markdown(f'### Peak Echelon {i+1}'))
    display(_echelon_indicator(echelon))

for i, echelon in enumerate(result.foundation_echelons):
    display(Markdown(f'### Foundation Echelon {i+1}'))
    display(_echelon_indicator(echelon))

### Peak Echelon 1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

### Peak Echelon 2

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

### Peak Echelon 3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

### Peak Echelon 4

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

### Foundation Echelon 1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

### Foundation Echelon 2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]], dtype=int8)

### Foundation Echelon 3

array([[1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [1, 1, 1, 1, 0]], dtype=int8)