# Two dimensional toy data

## Two-dim demo 2

In [9]:
# %load_ext autoreload
# %autoreload 2

from IPython.display import Markdown, display
import numpy as np

### Data
data = np.array([
    [2, 8, 24, 5, 3],
    [1, 10, 14, 22, 15],
    [4, 21, 19, 23, 25],
    [16, 20, 12, 11, 17],
    [13, 6, 9, 7, 18]
])

In [10]:
from echelon.api import TwoDimEchelonAnalysis
analyzer = TwoDimEchelonAnalysis()
result = analyzer(data)
result

/Users/teshima/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/numpy/lib/function_base.py:4454: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asarray(arr)


Result_EchelonAnalysis(peak_echelons=[[14, 13, 8], [2], [11, 16], [24]], foundation_echelons=[[12], [19, 15, 9], [7, 20, 17, 18, 6, 22, 1, 23, 21, 3, 10, 4, 0, 5]], oracle=<echelon.oracle.NdarrayEchelonOracle object at 0x7f845a25bd30>)

In [3]:
def _echelon_indicator(echelon):
    _W = np.zeros(data.shape, dtype='int8')
    for ind in echelon:
        _W[np.unravel_index(ind, shape=data.shape)] = 1
    return _W

for i, echelon in enumerate(result.peak_echelons):
    display(Markdown(f'### Peak Echelon {i+1}'))
    print(_echelon_indicator(echelon))

for i, echelon in enumerate(result.foundation_echelons):
    display(Markdown(f'### Foundation Echelon {i+1}'))
    print(_echelon_indicator(echelon))

### Peak Echelon 1

[[0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Peak Echelon 2

[[0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Peak Echelon 3

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]]


### Peak Echelon 4

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]


### Foundation Echelon 1

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Foundation Echelon 2

[[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [1 0 0 0 1]
 [0 0 0 0 0]]


### Foundation Echelon 3

[[1 1 0 1 1]
 [1 1 1 0 0]
 [1 0 0 0 0]
 [0 0 1 1 0]
 [1 1 1 1 0]]


In [4]:
from echelon.test import _visualize_echelons
print(_visualize_echelons(data.shape, result.peak_echelons, result.foundation_echelons))

[[7 7 2 7 7]
 [7 7 7 1 6]
 [7 3 5 1 1]
 [6 3 7 7 6]
 [7 7 7 7 4]]


## Two-dim demo 2
Example adopted from
* Kurihara K. (2004). Classification of geospatial lattice data and their graphical representation. Classification, Clustering, and Data Mining Applications, (Edited by D.Banks et al.) Springer, 251–258.

In [5]:
import numpy as np
from echelon.api import TwoDimEchelonAnalysis
from echelon.test import _visualize_echelons

data = np.array([
    [10, 24, 10, 15, 10],
    [10, 10, 14, 22, 10],
    [10, 13, 19, 23, 25],
    [20, 21, 12, 11, 17],
    [16, 10, 10, 18, 10]
])
analyzer = TwoDimEchelonAnalysis(adjacency_type='8')
result = analyzer(data)
print(_visualize_echelons(data.shape, result.peak_echelons, result.foundation_echelons))

[[7 2 7 6 7]
 [7 7 7 1 7]
 [7 7 5 1 1]
 [3 3 7 7 6]
 [6 7 7 4 7]]


/Users/teshima/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/numpy/lib/function_base.py:4454: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asarray(arr)
